name: Create Tagged Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: "Build Changelog & Release"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      # We fetch to 0 so we can collect the commits
      # since last update
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Download all modules
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Compress build output with zip
        run: |
          cd dist && zip -r ../monitor.zip .

      - name: Create and Upload Release
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: monitor.zip
